services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - app_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: "http://keycloak:8080"
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - app_network

# Define the network here
networks:
  app_network:
    driver: bridge

#
#  api-gateway:
#    container_name: api-gateway
#    build:
#      context: .
#      dockerfile: Dockerfile-api-gateway
#    ports:
#      - "9000:9000"
#    environment:
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/store
#      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
#      SPRINGDOC_API_DOCS_ENABLED: "true"
#    depends_on:
#      - keycloak
#    networks:
#      - app_network
#
#networks:
#  app_network:
